server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-customer
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/checkAgro-dev
    username: usr-checkAgro
    password: pwd-checkAgro

  jpa:
    generate-ddl: true
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
    show-sql: false

info:
  application:
    name: api-customer

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, health, info, ratelimiters, metrics
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

  # retry:
  #   configs:
  #     default:
  #       max-retry-attempts: 3
  #       wait-duration: 1s
  #       retry-exceptions:
  #         - java.io.IOException
  #         - java.net.SocketTimeoutException
  #     instances:
  #       retryCustomer:
  #         base-config: default
  #         max-retry-attempts: 5
  #         wait-duration: 2s
  #         retry-exceptions:
  #           - feign.FeignException$InternalServerError
  #           - o.s.c.l.core.RoundRobinLoadBalancer
resilience4j.circuitbreaker:
    instances:
      clientCustomer:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 15s
        failureRateThreshold: 50
        automaticTranstitionFromOpenToHalfOpenEnabled: true